const fs = require('fs');
const path = require('path');

const src = path.resolve(__dirname, '../readme.md');
const dest = path.resolve(__dirname, '../src/app/data/credits.generated.ts');

/**
 * Extracts the `# Credits` / `## Credits` section from the readme and renders it
 * as a small, trusted HTML snippet (links + list items). Mirrors the parsing that
 * previously ran in the browser, but done once at build time.
 */
function parseCreditsSection(markdown) {
  const creditsMatch = markdown.match(/^#{1,2}\s*Credits\s*$([\s\S]*)/m);
  if (!creditsMatch) {
    return '';
  }
  let creditsText = creditsMatch[1].trim();
  // Convert markdown links to HTML links
  creditsText = creditsText.replace(/\[([^\]]+)\]\(([^\)]+)\)/g, '<a href="$2" target="_blank" rel="noopener noreferrer">$1</a>');
  // Convert markdown list to HTML
  let html = creditsText.replace(/\* (.+)/g, '<li>$1</li>');
  if (/^<li>/.test(html)) {
    html = `<ul>${html}</ul>`;
  }
  return html;
}

const markdown = fs.readFileSync(src, 'utf8').replace(/\r\n/g, '\n');
const creditsHtml = parseCreditsSection(markdown);

const output = `// AUTO-GENERATED by scripts/generate-credits.js from readme.md.
// Do not edit by hand; run \`npm run generate-credits\` (also runs on prebuild).
export const CREDITS_HTML = ${JSON.stringify(creditsHtml)};
`;

fs.writeFileSync(dest, output);
console.log(`Wrote credits to ${path.relative(path.resolve(__dirname, '..'), dest)}`);
