// Nebula catalogue helpers. The data itself ships as a lazily-fetched JSON asset
// (`assets/nebulae.json`) generated by `scripts/generate-nebulae.js` from the EDAstro
// nebulae-coordinates CSV; the app never consumes the CSV directly.

export interface Nebula {
  /** Display name (e.g. "Witch Head Nebula" or a procedural planetary-nebula system name). */
  name: string;
  /** The in-game system the nebula is catalogued at; used to deep-link its signals page. */
  system: string;
  x: number;
  y: number;
  z: number;
  /** EDAstro classification: "real" (named), "planetary", or "procgen". */
  type: string;
}

export interface NearestNebula extends Nebula {
  /** Straight-line distance in light-years from the queried coordinates. */
  distance: number;
}

interface Coords {
  x: number;
  y: number;
  z: number;
}

/**
 * Returns the `count` nebulae closest to `coords`, nearest first, each annotated with
 * its straight-line distance in light-years. Returns an empty array when the catalogue
 * is empty (e.g. before the asset has loaded).
 */
export function findNearestNebulae(coords: Coords, nebulae: readonly Nebula[], count = 3): NearestNebula[] {
  if (count <= 0) {
    return [];
  }
  return nebulae
    .map(nebula => ({
      ...nebula,
      distance: Math.sqrt(
        (coords.x - nebula.x) ** 2 +
        (coords.y - nebula.y) ** 2 +
        (coords.z - nebula.z) ** 2,
      ),
    }))
    .sort((a, b) => a.distance - b.distance)
    .slice(0, count);
}
